# Generated by Django 3.2.15 on 2022-09-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftag_name', models.CharField(max_length=50, verbose_name='父标签名称')),
                ('ftag_description', models.TextField(verbose_name='父标签描述')),
                ('ftag_CreateDate', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
    ]
