# Generated by Django 3.2.15 on 2022-09-22 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_ftag_createdate_ftag_ftag_createdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('tag_description', models.TextField(verbose_name='标签描述')),
                ('tag_createdate', models.DateTimeField(verbose_name='创建时间')),
                ('ftag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ftag', verbose_name='父标签')),
            ],
        ),
    ]
