# Generated by Django 3.2.15 on 2022-09-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcategory_name', models.CharField(max_length=50, verbose_name='父分类名称')),
                ('fcategory_description', models.TextField(verbose_name='父标签描述')),
                ('fcategory_createdate', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
    ]
