# Generated by Django 3.2.15 on 2022-09-22 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_fcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('category_description', models.TextField(verbose_name='分类描述')),
                ('category_createdate', models.DateTimeField(verbose_name='创建时间')),
                ('fcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.fcategory', verbose_name='父分类')),
            ],
        ),
    ]
