# Generated by Django 3.2.15 on 2022-09-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='fcategory_id',
            new_name='fcategory',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='ftag_id',
            new_name='ftag',
        ),
    ]
