# Generated by Django 3.2.15 on 2022-09-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220922_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('user_nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户昵称')),
                ('user_sex', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('user_email', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户邮箱')),
                ('user_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='用户手机')),
                ('user_pwd', models.CharField(max_length=128, verbose_name='用户密码')),
                ('user_img', models.FileField(max_length=128, upload_to='usersimg/', verbose_name='用户头像')),
                ('user_createdate', models.DateTimeField(verbose_name='注册时间')),
                ('user_birth', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('user_auth', models.SmallIntegerField(choices=[(1, '普通权限'), (2, '管理员权限'), (3, '使用权限')], default=1, verbose_name='用户权限')),
                ('user_level', models.SmallIntegerField(choices=[(1, '普通'), (2, 'VIP'), (3, '超级VIP')], default=1, verbose_name='用户等级')),
            ],
        ),
    ]
