# Generated by Django 3.2.15 on 2022-09-22 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=32, verbose_name='博文标题')),
                ('article_digest', models.CharField(max_length=400, verbose_name='博文摘要')),
                ('article_content', models.TextField(verbose_name='博文内容')),
                ('article_createdate', models.DateTimeField(verbose_name='发表日期')),
                ('article_updatedate', models.DateTimeField(verbose_name='更新日期')),
                ('article_top', models.SmallIntegerField(choices=[(0, '不置顶'), (1, '置顶')], default=0, verbose_name='是否置顶')),
                ('article_view', models.BigIntegerField(default=0, verbose_name='浏览量')),
                ('article_like', models.BigIntegerField(default=0, verbose_name='点赞量')),
                ('article_comment', models.BigIntegerField(default=0, verbose_name='评论数')),
                ('article_collect', models.BigIntegerField(default=0, verbose_name='收藏量')),
                ('article_auth', models.SmallIntegerField(choices=[(0, '不共享'), (1, '共享')], default=1, verbose_name='共享权限')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category', verbose_name='博文分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.users', verbose_name='发表用户')),
            ],
        ),
    ]
