# Generated by Django 3.2.15 on 2022-09-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendslink_links', models.CharField(max_length=255, verbose_name='友链链接')),
                ('friendslink_name', models.CharField(max_length=32, verbose_name='友链名称')),
                ('friendslink_description', models.TextField(verbose_name='友链描述')),
                ('friendslink_logo', models.FileField(blank=True, null=True, upload_to='linkimg/', verbose_name='友链Logo')),
            ],
        ),
    ]
