# Generated by Django 3.2.15 on 2022-09-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_friendslink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='用户手机'),
        ),
    ]
