# Generated by Django 3.2.15 on 2022-09-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20220922_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='jumpaddress',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
