# Generated by Django 3.2.15 on 2022-09-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_category_jumpaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='jumpaddress',
            field=models.CharField(blank=True, default='#', max_length=128, null=True),
        ),
    ]
