# Generated by Django 3.2.15 on 2022-09-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_category_jumpaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_status',
            field=models.SmallIntegerField(choices=[(1, '草稿'), (2, '已发表')], default=1, verbose_name='发表状态'),
        ),
        migrations.AlterField(
            model_name='category',
            name='jumpaddress',
            field=models.CharField(default='#', max_length=128, verbose_name='跳转地址'),
        ),
    ]
