# Generated by Django 3.2.15 on 2022-09-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20220928_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_img',
            field=models.FileField(blank=True, null=True, upload_to='article_img/', verbose_name='文章贴图'),
        ),
    ]
