# Generated by Django 3.2.15 on 2022-10-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_articles_article_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_status',
            field=models.SmallIntegerField(choices=[(1, '草稿'), (2, '已发表'), (3, '审核中')], default=1, verbose_name='发表状态'),
        ),
    ]
