# Generated by Django 3.2.15 on 2022-10-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_articles_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_status',
            field=models.SmallIntegerField(choices=[(1, '草稿'), (2, '已发表'), (3, '审核中')], default=3, verbose_name='发表状态'),
        ),
    ]
