# Generated by Django 3.2.15 on 2022-10-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_articles_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_img',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文章贴图'),
        ),
    ]
