# Generated by Django 3.2.15 on 2022-10-16 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20221013_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='tag',
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_createdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 17, 17, 5, 372511), verbose_name='发表日期'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_createdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 17, 17, 5, 372091), verbose_name='注册时间'),
        ),
    ]
