# Generated by Django 3.2.15 on 2022-11-01 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20221016_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.users', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='fcategory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.users', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='ftag',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.users', verbose_name='所属用户'),
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.users', verbose_name='所属用户'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_createdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 10, 44, 27, 360839), verbose_name='发表日期'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_status',
            field=models.SmallIntegerField(choices=[(1, '草稿'), (2, '已发表'), (3, '审核中'), (4, '回收站')], default=3, verbose_name='发表状态'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_createdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 10, 44, 27, 359745), verbose_name='注册时间'),
        ),
    ]
