# Generated by Django 3.2.15 on 2022-11-05 16:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20221102_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='article_createdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 16, 9, 50, 601870), verbose_name='发表日期'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_createdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 16, 9, 50, 604582), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_fid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.comments', verbose_name='父评论'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_like',
            field=models.BigIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_createdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 5, 16, 9, 50, 600490), verbose_name='注册时间'),
        ),
    ]
