# Generated by Django 3.2.15 on 2022-12-08 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20221105_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='jumpaddress',
        ),
        migrations.AlterField(
            model_name='articles',
            name='article_createdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 11, 26, 9, 470704), verbose_name='发表日期'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_createdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 11, 26, 9, 474632), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_createdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 11, 26, 9, 468676), verbose_name='注册时间'),
        ),
    ]
